/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedControlTowerRouteImport } from './routes/_authenticated/control-tower'
import { Route as AuthenticatedCostingRouteImport } from './routes/_authenticated/costing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedWebsiteRouteImport } from './routes/_authenticated/website'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteOurAgentsRouteImport } from './routes/_site/our-agents'
import { Route as SiteOurProjectsRouteImport } from './routes/_site/our-projects'
import { Route as SitePartnersRouteImport } from './routes/_site/partners'
import { Route as SitePortfolioRouteImport } from './routes/_site/portfolio'
import { Route as SitePricingRouteImport } from './routes/_site/pricing'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteProductsRouteImport } from './routes/_site/products'
import { Route as SiteRequestRouteImport } from './routes/_site/request'
import { Route as SiteServicesRouteImport } from './routes/_site/services'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests.index'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated/requests.$id'
import { Route as AuthenticatedRequestsNewRouteImport } from './routes/_authenticated/requests.new'
import { Route as SiteNewsIndexRouteImport } from './routes/_site/news.index'
import { Route as SiteNewsSlugRouteImport } from './routes/_site/news.$slug'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedControlTowerRoute =
  AuthenticatedControlTowerRouteImport.update({
    id: '/control-tower',
    path: '/control-tower',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCostingRoute = AuthenticatedCostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebsiteRoute = AuthenticatedWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOurAgentsRoute = SiteOurAgentsRouteImport.update({
  id: '/our-agents',
  path: '/our-agents',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOurProjectsRoute = SiteOurProjectsRouteImport.update({
  id: '/our-projects',
  path: '/our-projects',
  getParentRoute: () => SiteRoute,
} as any)
const SitePartnersRoute = SitePartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => SiteRoute,
} as any)
const SitePortfolioRoute = SitePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRequestRoute = SiteRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsNewRoute =
  AuthenticatedRequestsNewRouteImport.update({
    id: '/requests/new',
    path: '/requests/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SiteNewsIndexRoute = SiteNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNewsSlugRoute = SiteNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/control-tower': typeof AuthenticatedControlTowerRoute
  '/costing': typeof AuthenticatedCostingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/website': typeof AuthenticatedWebsiteRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/our-agents': typeof SiteOurAgentsRoute
  '/our-projects': typeof SiteOurProjectsRoute
  '/partners': typeof SitePartnersRoute
  '/portfolio': typeof SitePortfolioRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/products': typeof SiteProductsRoute
  '/request': typeof SiteRequestRoute
  '/services': typeof SiteServicesRoute
  '/terms': typeof SiteTermsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/news/$slug': typeof SiteNewsSlugRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/news/': typeof SiteNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/control-tower': typeof AuthenticatedControlTowerRoute
  '/costing': typeof AuthenticatedCostingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/website': typeof AuthenticatedWebsiteRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/our-agents': typeof SiteOurAgentsRoute
  '/our-projects': typeof SiteOurProjectsRoute
  '/partners': typeof SitePartnersRoute
  '/portfolio': typeof SitePortfolioRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/products': typeof SiteProductsRoute
  '/request': typeof SiteRequestRoute
  '/services': typeof SiteServicesRoute
  '/terms': typeof SiteTermsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal': typeof PortalIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
  '/news/$slug': typeof SiteNewsSlugRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/news': typeof SiteNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/control-tower': typeof AuthenticatedControlTowerRoute
  '/_authenticated/costing': typeof AuthenticatedCostingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/website': typeof AuthenticatedWebsiteRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/our-agents': typeof SiteOurAgentsRoute
  '/_site/our-projects': typeof SiteOurProjectsRoute
  '/_site/partners': typeof SitePartnersRoute
  '/_site/portfolio': typeof SitePortfolioRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/products': typeof SiteProductsRoute
  '/_site/request': typeof SiteRequestRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/terms': typeof SiteTermsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_site/': typeof SiteIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/requests/new': typeof AuthenticatedRequestsNewRoute
  '/_site/news/$slug': typeof SiteNewsSlugRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_site/news/': typeof SiteNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/catalog'
    | '/control-tower'
    | '/costing'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/payments'
    | '/pipeline'
    | '/quotations'
    | '/reports'
    | '/search'
    | '/settings'
    | '/tasks'
    | '/website'
    | '/about'
    | '/contact'
    | '/our-agents'
    | '/our-projects'
    | '/partners'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/request'
    | '/services'
    | '/terms'
    | '/portal/$token'
    | '/portal/'
    | '/customers/$id'
    | '/orders/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/news/$slug'
    | '/customers/'
    | '/orders/'
    | '/requests/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approvals'
    | '/catalog'
    | '/control-tower'
    | '/costing'
    | '/dashboard'
    | '/documents'
    | '/notifications'
    | '/payments'
    | '/pipeline'
    | '/quotations'
    | '/reports'
    | '/search'
    | '/settings'
    | '/tasks'
    | '/website'
    | '/about'
    | '/contact'
    | '/our-agents'
    | '/our-projects'
    | '/partners'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/request'
    | '/services'
    | '/terms'
    | '/portal/$token'
    | '/portal'
    | '/customers/$id'
    | '/orders/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/news/$slug'
    | '/customers'
    | '/orders'
    | '/requests'
    | '/news'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/catalog'
    | '/_authenticated/control-tower'
    | '/_authenticated/costing'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/pipeline'
    | '/_authenticated/quotations'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/website'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/our-agents'
    | '/_site/our-projects'
    | '/_site/partners'
    | '/_site/portfolio'
    | '/_site/pricing'
    | '/_site/privacy'
    | '/_site/products'
    | '/_site/request'
    | '/_site/services'
    | '/_site/terms'
    | '/portal/$token'
    | '/_site/'
    | '/portal/'
    | '/_authenticated/customers/$id'
    | '/_authenticated/orders/$id'
    | '/_authenticated/requests/$id'
    | '/_authenticated/requests/new'
    | '/_site/news/$slug'
    | '/_authenticated/customers/'
    | '/_authenticated/orders/'
    | '/_authenticated/requests/'
    | '/_site/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalTokenRoute: typeof PortalTokenRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control-tower': {
      id: '/_authenticated/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof AuthenticatedControlTowerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costing': {
      id: '/_authenticated/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof AuthenticatedCostingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website': {
      id: '/_authenticated/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AuthenticatedWebsiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/our-agents': {
      id: '/_site/our-agents'
      path: '/our-agents'
      fullPath: '/our-agents'
      preLoaderRoute: typeof SiteOurAgentsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/our-projects': {
      id: '/_site/our-projects'
      path: '/our-projects'
      fullPath: '/our-projects'
      preLoaderRoute: typeof SiteOurProjectsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/partners': {
      id: '/_site/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof SitePartnersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/portfolio': {
      id: '/_site/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof SitePortfolioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/request': {
      id: '/_site/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof SiteRequestRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/new': {
      id: '/_authenticated/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthenticatedRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_site/news/': {
      id: '/_site/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof SiteNewsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/news/$slug': {
      id: '/_site/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof SiteNewsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedControlTowerRoute: typeof AuthenticatedControlTowerRoute
  AuthenticatedCostingRoute: typeof AuthenticatedCostingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedWebsiteRoute: typeof AuthenticatedWebsiteRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
  AuthenticatedRequestsNewRoute: typeof AuthenticatedRequestsNewRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedControlTowerRoute: AuthenticatedControlTowerRoute,
  AuthenticatedCostingRoute: AuthenticatedCostingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedWebsiteRoute: AuthenticatedWebsiteRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
  AuthenticatedRequestsNewRoute: AuthenticatedRequestsNewRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteOurAgentsRoute: typeof SiteOurAgentsRoute
  SiteOurProjectsRoute: typeof SiteOurProjectsRoute
  SitePartnersRoute: typeof SitePartnersRoute
  SitePortfolioRoute: typeof SitePortfolioRoute
  SitePricingRoute: typeof SitePricingRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteProductsRoute: typeof SiteProductsRoute
  SiteRequestRoute: typeof SiteRequestRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteNewsSlugRoute: typeof SiteNewsSlugRoute
  SiteNewsIndexRoute: typeof SiteNewsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteOurAgentsRoute: SiteOurAgentsRoute,
  SiteOurProjectsRoute: SiteOurProjectsRoute,
  SitePartnersRoute: SitePartnersRoute,
  SitePortfolioRoute: SitePortfolioRoute,
  SitePricingRoute: SitePricingRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteProductsRoute: SiteProductsRoute,
  SiteRequestRoute: SiteRequestRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteNewsSlugRoute: SiteNewsSlugRoute,
  SiteNewsIndexRoute: SiteNewsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalTokenRoute: PortalTokenRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
